apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teama-sgwsharness
  description: sgwsharness self service workflows
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/teama
  lifecycle: experimental
